#!/bin/bash

observer=

while getopts o: name
do
	case $name in
		o)
			observer=$OPTARG
			;;
	esac
done
shift $((OPTIND - 1))

[[ -z "$observer" ]] && observer=$(asciiworld-ip-geo)
[[ -z "$observer" ]] && exit 1

tmpdir=$(mktemp -d)
satdir=~/.cache/asciiworld-sat-track

mkdir -p "$satdir"
find "$satdir" -type f -mtime +0 -delete
track=()
for i
do
	if [[ ! -f "$satdir"/"$i".tle ]]
	then
		tle=$(asciiworld-sat-get "$i")
		(( $? != 0 )) && exit 1
		echo "$tle" >"$satdir"/"$i".tle
	fi
	track+=("$satdir"/"$i".tle)
done

tput civis
trap 'tput cnorm; rm -Rf "$tmpdir"' EXIT
while true
do
	echo -e "points\n$observer" >"$tmpdir"/loc
	for i in "${track[@]}"
	do
		asciiworld-sat-calc <"$i" >>"$tmpdir"/loc
		(( $? != 0 )) && exit 1
	done
	asciiworld -Tosl "$tmpdir"/loc -d ast
	(( $? != 0 )) && exit 1
	sleep 0.5
	tput home
done
