#!/usr/bin/env python


from pygeoip import GeoIP
import sys


# Path to the database, Arch Linux, package geoip-citydata. Replace this
# with an appropriate path on your system.
geoip_city_database = "/usr/share/GeoIP/GeoIPCity.dat"

gi = GeoIP(geoip_city_database)
gir = gi.record_by_addr(sys.argv[1])
if gir is not None:
    print('{} {}'.format(gir['latitude'], gir['longitude']))
