#!/bin/bash

observer=$1

track=$(mktemp)
tput civis
trap 'rm -f "$track"; tput cnorm' EXIT

while true
do
	: >"$track"
	ss -4tun |
	gawk 'NR != 1 { split($6, s, ":"); print s[1] }' |
	sort |
	uniq |
	while read ip
	do
		res=$(asciiworld-ip-geo "$ip")
		(( $? != 0 )) && exit 1
		if [[ -n "$res" ]]
		then
			lat=${res% *}
			lon=${res#* }
			asciiworld-waypoints "$observer" "$lat $lon" >>"$track"
			(( $? != 0 )) && exit 1
		fi
	done

	asciiworld -Tosl "$track"
	(( $? != 0 )) && exit 1
	sleep 2
	tput home
done
