#!/bin/bash

# This has been tested for two maps:
# https://commons.wikimedia.org/wiki/File:World_map_-_low_resolution.svg
# https://en.wikipedia.org/wiki/File:Worldmap_location_NED_50m.svg
# Don't complain about this not working with other maps.

svg=${1:-World_map_-_low_resolution.svg}
output=${2:-world.map}

viewbox=$(xmlstarlet sel -t -m //svg:svg -v $'concat(@viewBox, "\n")' "$svg")
if [[ -n "$viewbox" ]]
then
	echo "$viewbox" | awk '{
		x = $1
		y = $2
		w = $3
		h = $4
		print (w - x) " " (h - y)
	}' >"$output"
else
	xmlstarlet sel -t -m //svg:svg -v $'concat(@width, " ", @height, "\n")' "$svg" >"$output"
fi

xmlstarlet sel -t -m //svg:path -v $'concat(@d, "\n")' "$svg" |
sed -r 's/[a-zA-Z]/ & /g; s/,/ /g; s/([0-9.])-([0-9])/\1 -\2/g; s/^ //; s/ +$//' |
sed -r 's/Z/z/g; /^$/d; s/[^z]$/& z/; s/ +/ /g' |
sed -r 's/(.)M/\1\nM/g' |
perl -ne 's/([-0-9.]+ [-0-9.]+)((?= [-0-9.])|(?= z))/L \1/g; print' |
sed -r 's/^M L/M/; s/L L/L/g; s/ +$//' >>"$output"
