#!/bin/bash

observer=$1
shift

tmpdir=$(mktemp -d)
satdir=~/.cache/tracksats

mkdir -p "$satdir"
track=()
for i
do
	if [[ ! -f "$satdir"/"$i".tle ]]
	then
		tle=$(./getsat "$i")
		(( $? != 0 )) && exit 1
		echo "$tle" >"$satdir"/"$i".tle
	fi
	track+=("$satdir"/"$i".tle)
done

tput civis
trap 'tput cnorm; rm -Rf "$tmpdir"' EXIT
while true
do
	echo -e "points\n$observer" >"$tmpdir"/loc
	for i in "${track[@]}"
	do
		./calcsat <"$i" >>"$tmpdir"/loc
		(( $? != 0 )) && exit 1
	done
	./asciiworld -Tosl "$tmpdir"/loc -d ast
	(( $? != 0 )) && exit 1
	sleep 0.5
	tput home
done
